#include<stdio.h>
#include<unistd.h>
#include<sys/types.h>
void main()
{
   int PID_PARENT=getpid();
   int n;
   printf("Enter the value of n : ");
   scanf("%d",&n);
   printf("------------------------------------------");
   printf("\nPID of parent process: %d\n",PID_PARENT);
   fork();
   //printf("PID : %d\n",getpid());
   if(getpid()!=PID_PARENT)
   {
     printf("\nFIBONACCI Series generated by child process PID = %d\n",getpid());
     int a=0,b=1;
     int c;
     printf("%d ",a);
     printf("%d ",b);
     for(int i=2;i<n;i++)
     {
       c=a+b;
       printf("%d ",c);
       a=b;
       b=c;
     }
     printf("\n");
     printf("------------------------------------------");
     printf("\n");
   }
   else
   {
     printf("\nFirst %d prime numbers printed by parent process PID = %d\n",n,getpid());
     int count=1;
     int i=2;
     int j;
     printf("2 ");
     for(int i=3;count<n;i++)
     {
       for(j=2;j<i;j++)
       {
         if(i%j==0)
           break;
       }
       
       if(j==i)
       {
         printf("%d ",j);
         count++;
       }
   }
   printf("\n");
  }
 }
